# Generated by Django 6.0.6 on 2026-06-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prior_avg_demand',
            field=models.FloatField(default=0, help_text='Your best estimate of weekly demand. Used as a starting point that phases out automatically once 4 weeks of real sales are recorded.'),
        ),
    ]
